services:

  htrocky:
    image: my_rocky_image
    build:
      context: ./rocky
      args:
        GIT_REPO_VERSION: "2938"
    network_mode: host
    ports:
      - "9618:9618"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/condor:/var/lib/condor
      - /home:/home
    env_file:
      - .env
  jupyterhub:
    image: my_jupyterhub-jupyterhub
    build: 
      context: ./jupy
    env_file:
      - .env
    networks:
      - jupyternet
    ports:
      - "8555:8555"
    volumes:
      - ./jupy/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
      - ./jupy/jupyter.token:/srv/jupyterhub/jupyter.token
      - /var/run/docker.sock:/var/run/docker.sock
      
  notebook:
    depends_on:
      - jupyterhub
      - htrocky
    image: jnotebook_image
    build:
      context: ./jupy/notebook
    networks:
      - jupyternet

  nginx:
    image: nginx_image
    build:
      context: ./nginx
    ports:
      - "443:443"
    networks:
      - jupyternet
    depends_on:
      - jupyterhub
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "hub.local:127.0.0.1"

networks:
  jupyternet:
    driver: overlay
    attachable: true
