version: '3'

services:
  jupyterhub:
    image: my_jupyterhub-jupyterhub
    build: 
      context: ./jupy
    networks:
      - jupyternet
    ports:
      - "8000:8000"
    volumes:
      - ./jupy/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
      - ./jupy/jupyter.token:/srv/jupyterhub/jupyter.token
      - /var/run/docker.sock:/var/run/docker.sock

  htrocky:
    image: my_rocky_image
    build:
      context: ./rocky
    networks:
      - jupyternet
    ports:
      - "9618:9618"
    volumes:
      - ./rocky/test.sh:/work/test.sh

networks:
  jupyternet:
    driver: overlay
    attachable: true
