version: '3'

services:
  htgate:
    image: htgate:latest
    platform: linux/amd64
    restart: unless-stopped
    build:
      context: .
      dockerfile: rocky/Dockerfile
      pull: true
    ports:
      - "9618:9618"
    volumes:
      - .:/work
  jupyterhub:
    image: my_jupyterhub-jupyterhub
    build: .
    networks:
      - jupyternet
    ports:
      - "8000:8000"
    volumes:
      - ./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
      - ./jupyter.token:/srv/jupyterhub/jupyter.token
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  jupyternet:
    driver: overlay
    attachable: true