version: '3'

services:
  jupyterhub:
    image: my_jupyterhub-jupyterhub
    build: .
    networks:
      - jupyternet
    ports:
      - "8000:8000"
    volumes:
      - ./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
      - ./jupyter.token:/srv/jupyterhub/jupyter.token
      - /var/run/docker.sock:/var/run/docker.sock

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - jupyterhub

networks:
  jupyternet:
    driver: overlay
    attachable: true