services:

  htrocky:
    image: my_rocky_image
    build:
      context: ./rocky
      args:
        GIT_REPO_VERSION: "84d4dwdhdweddj46aa"
    networks:
      - jupyternet
    ports:
      - "9618:9618"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/condor:/var/lib/condor
      - /home:/home
  jupyterhub:
    image: my_jupyterhub-jupyterhub
    build: 
      context: ./jupy
    networks:
      - jupyternet
    ports:
      - "8555:8555"
    volumes:
      - ./jupy/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
      - ./jupy/jupyter.token:/srv/jupyterhub/jupyter.token
      - /var/run/docker.sock:/var/run/docker.sock
      
  notebook:
    depends_on:
      - jupyterhub
      - htrocky
    image: jnotebook_image
    build:
      context: ./jupy/notebook
    networks:
      - jupyternet

networks:
  jupyternet:
    driver: overlay
    attachable: true
